# Generated by Django 3.1.5 on 2021-01-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(),
        ),
    ]
