# Generated by Django 3.1.5 on 2021-03-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
