# Generated by Django 3.1.5 on 2021-04-02 16:08

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20210314_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverage',
            field=models.FileField(default=True, null=True, upload_to=books.models.book_upload_coverage),
        ),
    ]
