# Generated by Django 3.1.5 on 2021-04-02 20:20

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20210402_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverage',
            field=models.FileField(default='settings.MEDIA_ROOT/coverage/default/image.jpg', null='settings.MEDIA_ROOT/coverage/default/image.jpg', upload_to=books.models.book_upload_coverage),
        ),
    ]
