# Generated by Django 3.1.5 on 2021-04-11 11:22

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20210411_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverage',
            field=models.FileField(default=True, null=True, upload_to=books.models.book_upload_coverage),
        ),
    ]
