# Generated by Django 3.1.5 on 2021-04-11 11:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_upload_avatar),
        ),
    ]
